export const IMAGE_KEYS = {
    TEMP_POST_CONTAINER: "TEMP_POST_CONTAINER",
    TEMP_SPRITE: "TEMP_SPRITE"
};

export const SCENE_KEYS = {
    LOAD_SCENE: "LOAD_SCENE",
    TEST_SCENE: "TEST_SCENE",
    GAME_SCENE: "GAME_SCENE",
    PAUSE_SCENE: "PAUSE_SCENE",
    INFO_SCENE: "INFO_SCENE",
    MAIN_MENU_SCENE: "MAIN_MENU_SCENE",
};

export const JSON_KEYS = {
    POST_LIST: "POST_LIST",
    INFO_DB : "INFO_DB"
};