export const IMAGE_KEYS = {
    TEMP_POST_CONTAINER: "TEMP_POST_CONTAINER",
    TEMP_SPRITE: "TEMP_SPRITE",
    ICOSAMUEL: "ICOSAMUEL_SPRITESHEET",
    BACKGROUND_TRIANGLE: "BACKGROUND_TRIANGLE",
    BACKGROUND_TRIANGLES: "BACKGROUND_TRIANGLES",
    INSPECTOR_BUTTON: "INSPECTOR_BUTTON",
    CHRONO_CLOCK: 'CHRONO_CLOCK',
    BOOST_STAR: 'BOOST_STAR',
    CIRCLAUDIA: 'Circlaudia',
    CUADRICIO: 'Cuadricio',
    PENTADEO:'Pentadeo',
    HEXANDRA: 'Hexandra',
    TRICTORIA: 'Trictoria',
    ACCEPT: 'ACCEPT',
    DECLINE: 'DECLINE'
};

export const SCENE_KEYS = {
    LOAD_SCENE: "LOAD_SCENE",
    TEST_SCENE: "TEST_SCENE",
    GAME_SCENE: "GAME_SCENE",
    PAUSE_SCENE: "PAUSE_SCENE",
    INFO_SCENE: "INFO_SCENE",
    MAIN_MENU_SCENE: "MAIN_MENU_SCENE",
    TRAINING_MENU_SCENE: "TRAINING_MENU_SCENE",
    PUNCTUATION_SCENE: "PUNCTUATION_SCENE",
    TUTORIAL_SCENE: "TUTORIAL_SCENE"
};

export const JSON_KEYS = {
    POST_LIST: "POST_LIST",
    INFO_DB : "INFO_DB"
};

export const ANIM_KEYS = {
    ICOSAMUEL_IDLE: "ICOSAMUEL_IDLE",
    ICOSAMUEL_DANCE: "ICOSAMUEL_DANCE",
    ICOSAMUEL_RIGHT: "ICOSAMUEL_RIGHT"
}