export const TEXT_CONFIG = {
    Title:{
        fontSize:"132px",
        fontFamily:"Horizon"
    },
    Heading:{
        fontSize:"72px",
        fontFamily:"Horizon"
    },
    SubHeading:{
        fontSize:"32px",
        fontFamily:"Horizon"
    },
    Paragraph:{
        fontSize:"24px",
        fontFamily:"Oswald-Medium"
    },
    ParagraphBold:{
        fontSize:"24px",
        fontFamily:"Oswald-Bold"
    },
    ParagraphLight:{
        fontSize:"24px",
        fontFamily:"Oswald-Light"
    },
}